"""empty message

Revision ID: 16dc320c1715
Revises: d9067adb5b7d
Create Date: 2022-08-19 14:11:43.359866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dc320c1715'
down_revision = 'd9067adb5b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add__contact', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'add__contact', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'add__contact', type_='foreignkey')
    op.drop_column('add__contact', 'user_id')
    # ### end Alembic commands ###
