"""empty message

Revision ID: 98c9a58cad38
Revises: 4b044b2d30c5
Create Date: 2022-08-20 10:58:36.953156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c9a58cad38'
down_revision = '4b044b2d30c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('add__contact', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'add__contact', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'add__contact', type_='foreignkey')
    op.drop_column('add__contact', 'user_id')
    # ### end Alembic commands ###
